# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['python\\main.py'],
    pathex=[],
    binaries=[],
    datas=[('python/DAD_Utils.py', '.'), ('python/gui.py', '.'), ('python/config.py', '.')],
    hidden_imports = [
        "beautifulsoup4",
        "certifi",
        "charset_normalizer",
        "filelock",
        "fsspec",
        "html5lib",
        "idna",
        "jinja2",
        "keyboard",
        "lxml",
        "MarkupSafe",
        "MouseInfo",
        "mpmath",
        "networkx",
        "numpy",
        "opencv_python",
        "packaging",
        "pillow",
        "psutil",
        "PyAutoGUI",
        "pygame",
        "pygame_gui",
        "PyGetWindow",
        "PyMsgBox",
        "pynput",
        "pyperclip",
        "PyQt5",
        "PyQt5.QtCore",
        "PyQt5.QtGui",
        "PyQt5.QtWidgets",
        "PyQt6",
        "PyQt6.QtCore",
        "PyQt6.QtGui",
        "PyQt6.QtWidgets",
        "PyRect",
        "PyScreeze",
        "pytesseract",
        "python_i18n",
        "pytweening",
        "requests",
        "screeninfo",
        "setuptools",
        "six",
        "soupsieve",
        "sympy",
        "torch",
        "torchvision",
        "typing_extensions",
        "urllib3",
        "webencodings"
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SquireBot',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
